# Generated by Django 5.0.1 on 2024-04-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctorportal", "0002_appointment_amount_alter_doctor_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="available_days",
        ),
        migrations.AddField(
            model_name="doctor",
            name="available_days",
            field=models.ManyToManyField(to="doctorportal.day"),
        ),
    ]
