# Generated by Django 5.0.1 on 2024-04-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctorportal", "0003_day_remove_doctor_available_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="available_time",
        ),
        migrations.AddField(
            model_name="doctor",
            name="end_time",
            field=models.TimeField(default="23:59:59"),
        ),
        migrations.AddField(
            model_name="doctor",
            name="start_time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
