# Generated by Django 5.0.1 on 2024-04-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctorportal", "0004_remove_doctor_available_time_doctor_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
