# Generated by Django 5.0.1 on 2024-02-02 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("whatsapp_number", models.CharField(max_length=15)),
                ("alternate_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("speciality", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=50)),
                ("available_days", models.CharField(max_length=100)),
                ("available_time", models.CharField(max_length=100)),
                ("geographical_areas", models.TextField()),
                ("photo", models.ImageField(upload_to="doctors_photos/")),
                (
                    "degree_certificate",
                    models.ImageField(upload_to="doctors_certificates/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("appointment_time", models.DateTimeField()),
                ("number_of_sessions", models.IntegerField()),
                ("rx_complete", models.BooleanField(default=False)),
                ("amount_paid", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctorportal.doctor",
                    ),
                ),
            ],
        ),
    ]
